import * as THREE from 'three';

const cid=()=>sessionStorage.getItem('survival_character_id')||'guest';
const progKey=()=>`survival_progression_${cid()}`;
const invKey=()=>`survival_inventory_${cid()}`;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const xpForLevel=l=>Math.round(70*Math.pow(Math.max(0,l-1),1.55));
const totalForLevel=l=>{let t=0;for(let i=2;i<=l;i++)t+=xpForLevel(i);return t};
const readProg=()=>{try{return {level:1,xp:0,...JSON.parse(localStorage.getItem(progKey())||'{}')}}catch{return{level:1,xp:0}}};
const saveProg=p=>localStorage.setItem(progKey(),JSON.stringify(p));
const readInv=()=>{try{return JSON.parse(localStorage.getItem(invKey())||'{}')}catch{return{}}};
const saveInv=v=>{localStorage.setItem(invKey(),JSON.stringify(v));window.refreshInventoryQuantityBadges?.();window.refreshInventoryVisibility?.();window.refreshGroundInventory?.()};

const TIERS=[
 {id:1,min:1,max:10,name:'Survie primitive / branchages'},
 {id:2,min:11,max:20,name:'Bois'},
 {id:3,min:21,max:30,name:'Pierre'},
 {id:4,min:31,max:50,name:'Défense / métallurgie / fer'},
 {id:5,min:51,max:60,name:'Forteresse / château'}
];
const tierFor=l=>TIERS.find(t=>l>=t.min&&l<=t.max)||TIERS[TIERS.length-1];

const RES={
 branches:{name:'Branches',icon:'🌿',level:1,color:0x7f633d},wood:{name:'Bois',icon:'🪵',level:2,color:0x70502f},fiber:{name:'Fibres / paille',icon:'🌾',level:1,color:0xbda55b},dirt:{name:'Terre',icon:'🟫',level:3,color:0x76513b},clay:{name:'Argile',icon:'🧱',level:5,color:0x9b6047},sand:{name:'Sable',icon:'🏖️',level:3,color:0xcdb978},stone:{name:'Pierre',icon:'🪨',level:2,color:0x777a76},limestone:{name:'Calcaire',icon:'⬜',level:21,color:0xc8c6b5},copper:{name:'Cuivre',icon:'🟠',level:35,color:0xb66d3e},tin:{name:'Étain',icon:'⚪',level:36,color:0x9fa6aa},iron:{name:'Fer',icon:'⛓️',level:38,color:0x555b60},salt:{name:'Sel',icon:'🧂',level:24,color:0xe7e5da},hide:{name:'Peau',icon:'🟤',level:6,color:0x7b5135},fur:{name:'Fourrure',icon:'🐺',level:14,color:0x77716a},wool:{name:'Laine',icon:'☁️',level:18,color:0xe7e1d2},textilePlants:{name:'Plantes textiles',icon:'🌱',level:12,color:0x678c4b},bone:{name:'Os / cornes / dents',icon:'🦴',level:8,color:0xd9d0b7},fat:{name:'Graisse animale',icon:'🟡',level:9,color:0xc8a85f},medicinal:{name:'Plantes médicinales',icon:'🌿',level:7,color:0x4e944f},venom:{name:'Venins / glandes',icon:'🧪',level:32,color:0x6ca04b},resin:{name:'Résine',icon:'🟠',level:13,color:0xb17a34},ice:{name:'Glace',icon:'🧊',level:23,color:0xa9d8e8},basalt:{name:'Roche volcanique / basalte',icon:'⬛',level:31,color:0x363536},obsidian:{name:'Obsidienne',icon:'🔮',level:42,color:0x241f31},sulfur:{name:'Soufre',icon:'🟨',level:40,color:0xc5ad37},gold:{name:'Or',icon:'🟡',level:47,color:0xd5aa32},silver:{name:'Argent',icon:'⚪',level:44,color:0xbec6ca},water:{name:'Eau',icon:'💧',level:1,color:0x4aa4cc}
};
window.survivalResourceDefs=RES;

const UNLOCKS={
1:['Ramassage à la main','Feu de camp','Branches','Fibres / paille','Eau'],2:['Hache primitive','Pioche primitive','Pierre','Bois'],3:['Fondation branchages','Mur branchages','Toit chaume','Pelle primitive'],4:['Boue','Lit de fortune','Gourde'],5:['Rangement primitif','Argile'],6:['Lance primitive','Peau'],7:['Plantes médicinales','Arc primitif'],8:['Os / cornes / dents','Torchis'],9:['Graisse animale','Établi primitif','Cuisson simple'],10:['Palissade','Rondins','Poutres grossières'],
11:['Fondations bois','Murs bois','Plafonds bois'],12:['Plantes textiles','Planches'],13:['Résine','Poutres travaillées'],14:['Fourrure','Bouclier bois'],15:['Coffre amélioré','Culture simple'],16:['Collecteur d’eau','Tenue en peau'],17:['Mobilier bois','Défenses bois'],18:['Laine','Étages bois'],19:['Apprivoisement','Monture simple'],20:['Écurie','Selle','Transition pierre'],
21:['Pierre brute','Calcaire','Fondation pierre'],22:['Murs pierre','Taille de pierre'],23:['Glace','Plafond pierre'],24:['Sel','Cuisine conservée'],25:['Tours de guet','Escaliers pierre'],26:['Portes renforcées','Remparts'],27:['Créneaux','Armure cuir'],28:['Pont pierre','Défenses lourdes'],29:['Atelier de maçon'],30:['Puits','Cuve en pierre'],
31:['Basalte','Défenses avancées'],32:['Venins / glandes','Pièges avancés'],33:['Baliste primitive'],34:['Fortifications renforcées'],35:['Cuivre','Fourneau'],36:['Étain','Bronze'],37:['Forge améliorée'],38:['Fer','Outils en fer'],39:['Armes en fer'],40:['Soufre','Armure en fer'],41:['Agriculture avancée'],42:['Obsidienne','Lames rares'],43:['Cuisine avancée'],44:['Argent','Équipement argent'],45:['Montures avancées'],46:['Fortins'],47:['Or','Orfèvrerie'],48:['Ateliers spécialisés'],49:['Équipement lourd'],50:['Transition forteresse'],
51:['Fondations forteresse'],52:['Murs forteresse'],53:['Tours fortifiées'],54:['Portes de château'],55:['Remparts de château'],56:['Grand hall'],57:['Armurerie royale'],58:['Écuries fortifiées'],59:['Donjon'],60:['Équipement maximal','Château complet']
};
window.survivalLevelUnlocks=UNLOCKS;

let state={scene:null,camera:null,ready:false,nodes:[],lastNearest:null};
const oldRender=THREE.WebGLRenderer.prototype.render;
THREE.WebGLRenderer.prototype.render=function(scene,camera){state.scene=scene;state.camera=camera;if(!state.ready&&scene.children.length>6){state.ready=true;setTimeout(initWorldResources,300)}return oldRender.call(this,scene,camera)};

function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__progToast);window.__progToast=setTimeout(()=>e.classList.remove('show'),1800)}
function addXP(amount,reason=''){let p=readProg(),old=p.level;p.xp+=Math.max(0,amount);while(p.level<60&&p.xp>=totalForLevel(p.level+1))p.level++;saveProg(p);refreshHud();if(p.level>old){const t=tierFor(p.level),u=UNLOCKS[p.level]||[];toast(`NIVEAU ${p.level} • ${t.name}${u.length?' • '+u.join(', '):''}`);window.dispatchEvent(new CustomEvent('survival-level-up',{detail:{level:p.level,tier:t.id,unlocks:u}}))}else if(reason)toast(`+${amount} EXP • ${reason}`)}
window.addSurvivalXP=addXP;

function ensureHud(){if(document.getElementById('progressionHud'))return;const s=document.createElement('style');s.textContent=`.prog-hud{position:fixed;z-index:29;left:10px;top:142px;width:124px;padding:6px;background:#081118cf;border:1px solid #d6b45b55;border-radius:7px;color:#fff;font-size:7px;backdrop-filter:blur(3px)}.prog-line{display:flex;justify-content:space-between;gap:6px}.prog-line b{color:#efd17e}.prog-bar{height:5px;margin:5px 0 3px;background:#0009;border-radius:99px;overflow:hidden}.prog-bar i{display:block;height:100%;background:linear-gradient(90deg,#617f45,#d2ad55)}.prog-tier{color:#b9c8ca}.resource-action{position:fixed;z-index:33;right:102px;bottom:292px;width:98px;min-height:44px;padding:6px;border-radius:11px;border:1px solid #cda95f88;background:#142118df;color:#f2dda4;font-size:8px;font-weight:900}.resource-action[hidden]{display:none}.unlock-panel{position:fixed;z-index:58;left:50%;top:50%;transform:translate(-50%,-50%);width:min(88vw,430px);max-height:70vh;overflow:auto;background:#091217f5;border:1px solid #c8a55788;border-radius:14px;padding:14px;color:#fff;box-shadow:0 20px 60px #000b}.unlock-panel h3{margin:0 0 9px;color:#edcf82}.unlock-row{padding:7px;border-bottom:1px solid #ffffff12;font-size:9px}.unlock-row.locked{opacity:.4}.unlock-close{float:right;background:#ffffff12;color:#fff;border:0;border-radius:7px;padding:5px 8px}`;document.head.appendChild(s);const h=document.createElement('div');h.id='progressionHud';h.className='prog-hud';h.innerHTML=`<div class="prog-line"><b id="progLevel">NIV. 1</b><span id="progXp">0 EXP</span></div><div class="prog-bar"><i id="progFill"></i></div><div id="progTier" class="prog-tier"></div>`;h.onclick=openUnlocks;document.body.appendChild(h);const b=document.createElement('button');b.id='resourceAction';b.className='resource-action';b.hidden=true;document.body.appendChild(b);b.onclick=harvestNearest;refreshHud()}
function refreshHud(){ensureHud();const p=readProg(),next=p.level<60?totalForLevel(p.level+1):p.xp,cur=totalForLevel(p.level),pct=p.level>=60?100:clamp((p.xp-cur)/(next-cur)*100,0,100),t=tierFor(p.level);document.getElementById('progLevel').textContent=`NIV. ${p.level}`;document.getElementById('progXp').textContent=p.level>=60?'MAX':`${Math.max(0,p.xp-cur)}/${Math.max(1,next-cur)} EXP`;document.getElementById('progFill').style.width=pct+'%';document.getElementById('progTier').textContent=`Palier ${t.id} • ${t.name}`}
function openUnlocks(){document.getElementById('unlockPanel')?.remove();const p=readProg(),box=document.createElement('div');box.id='unlockPanel';box.className='unlock-panel';box.innerHTML=`<button class="unlock-close">✕</button><h3>Progression automatique</h3><div style="font-size:8px;color:#aebdc0;margin-bottom:8px">Niveau ${p.level}/60 • aucun point à dépenser</div>`;for(let l=1;l<=60;l++){const r=document.createElement('div');r.className='unlock-row'+(l>p.level?' locked':'');r.innerHTML=`<b>Niv. ${l}</b> — ${(UNLOCKS[l]||[]).join(' • ')||'Progression'}`;box.appendChild(r)}box.querySelector('button').onclick=()=>box.remove();document.body.appendChild(box)}

function addRows(){const bag=document.querySelector('#inventoryPanel .bag-view');if(!bag)return;for(const [k,d] of Object.entries(RES)){if(['wood','stone','water','dirt','sand','hide'].includes(k))continue;if(bag.querySelector(`[data-item="${k}"]`))continue;const r=document.createElement('div');r.className='inv-row';r.dataset.item=k;r.innerHTML=`<span>${d.icon} ${d.name}</span><b id="invProg_${k}">0</b>`;bag.appendChild(r)}refreshRows()}
function refreshRows(){const v=readInv();document.querySelectorAll('[id^="invProg_"]').forEach(e=>{const k=e.id.slice(8);e.textContent=v[k]||0;e.closest('[data-item]')?.toggleAttribute('hidden',!(v[k]>0))})}

const groundY=(x,z)=>{if(!state.scene)return 1;const ray=new THREE.Raycaster(new THREE.Vector3(x,300,z),new THREE.Vector3(0,-1,0),0,500);const hits=ray.intersectObjects(state.scene.children,true).filter(h=>!h.object.userData.progressionNode&&!h.object.userData.animal);return hits[0]?.point.y??1};
function nodeMesh(key,d){let mesh;if(['fiber','textilePlants','medicinal','resin'].includes(key)){mesh=new THREE.Mesh(new THREE.ConeGeometry(1.1,2.4,6),new THREE.MeshStandardMaterial({color:d.color,roughness:1}))}else if(['hide','fur','wool','bone','fat','venom'].includes(key)){mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1.3,0),new THREE.MeshStandardMaterial({color:d.color,roughness:.9}))}else{mesh=new THREE.Mesh(new THREE.DodecahedronGeometry(1.7,0),new THREE.MeshStandardMaterial({color:d.color,roughness:.85,metalness:['copper','tin','iron','gold','silver'].includes(key)?.35:0}))}mesh.userData.progressionNode=true;mesh.userData.resourceKey=key;return mesh}
function initWorldResources(){if(!state.scene)return;const keys=Object.keys(RES).filter(k=>!['water','wood','stone','dirt','sand','hide','branches'].includes(k));let i=0;for(const key of keys){const d=RES[key];for(let n=0;n<3;n++){const a=((i*2.399+n*.91)%6.283),r=150+((i*79+n*131)%480),x=Math.cos(a)*r,z=Math.sin(a)*r,y=groundY(x,z);if(y<.5)continue;const m=nodeMesh(key,d);m.position.set(x,y+1.1,z);m.scale.setScalar(.7+(n*.12));m.userData.level=d.level;m.userData.amount=1+(d.level>30?1:2);state.scene.add(m);state.nodes.push(m)}i++}setInterval(updateNearest,220)}
function nearestNode(){if(!state.camera)return null;let best=null,dist=9;for(const n of state.nodes){if(!n.visible)continue;const d=n.position.distanceTo(state.camera.position);if(d<dist){dist=d;best=n}}return best}
function updateNearest(){const b=document.getElementById('resourceAction');if(!b)return;const n=nearestNode();state.lastNearest=n;if(!n){b.hidden=true;return}const d=RES[n.userData.resourceKey],p=readProg();b.hidden=false;b.textContent=p.level<d.level?`🔒 ${d.name} • NIV ${d.level}`:`${d.icon} RÉCOLTER ${d.name.toUpperCase()}`}
function harvestNearest(){const n=nearestNode();if(!n)return;const key=n.userData.resourceKey,d=RES[key],p=readProg();if(p.level<d.level){toast(`${d.name} se débloque au niveau ${d.level}`);return}const v=readInv(),amt=n.userData.amount||1;v[key]=(v[key]||0)+amt;saveInv(v);refreshRows();n.visible=false;addXP(6+Math.floor(d.level/8),d.name);setTimeout(()=>{n.visible=true},45000)}

function hookExistingActions(){let before=null;document.addEventListener('pointerdown',e=>{if(e.target.closest('#gatherBtn,#digBtn,.hunt-btn,.craft-btn,#buildModeBtn'))before=readInv()},true);document.addEventListener('click',e=>{const t=e.target.closest('#gatherBtn,#digBtn,.hunt-btn,.craft-btn,#buildModeBtn');if(!t)return;const prev=before||readInv();setTimeout(()=>{const now=readInv();let gain=0,reason='Action';for(const [k,v] of Object.entries(now)){const delta=(Number(v)||0)-(Number(prev[k])||0);if(delta>0){gain+=delta*(t.matches('.hunt-btn')?8:t.matches('.craft-btn')?5:3);reason=RES[k]?.name||'Survie'}}if(gain>0)addXP(clamp(gain,3,45),reason);before=null},120)},true)}

function init(){ensureHud();addRows();hookExistingActions();setInterval(()=>{refreshHud();refreshRows()},1200)}
init();
