import * as THREE from 'three';
let character=null,px=0,pz=0,moveX=0,moveY=0,yaw=0,pitch=-.06,third=false,lastSave=0,lastTime=performance.now();
const SIZE=1600,WATER=0,MAP_RES=480,SCALE=SIZE/1100;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fcbe1);scene.fog=new THREE.FogExp2(0xa8d4df,.00088);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,2700);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.45));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.getElementById('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd7efff,0x526044,2.0));const sun=new THREE.DirectionalLight(0xffdfaa,2.7);sun.position.set(-260,430,180);sun.castShadow=true;scene.add(sun);
const fract=v=>v-Math.floor(v),noise=(x,z)=>fract(Math.sin(x*12.9898+z*78.233)*43758.5453),gauss=(x,z,cx,cz,s)=>Math.exp(-((x-cx)**2+(z-cz)**2)/(s*s)),clamp01=v=>Math.max(0,Math.min(1,v)),smooth=(a,b,v)=>{const t=clamp01((v-a)/(b-a));return t*t*(3-2*t)},lerp=(a,b,t)=>a+(b-a)*t;
const U=(x,z)=>({x:x/SCALE,z:z/SCALE});
function islandMask(x,z){const p=U(x,z),bx=p.x,bz=p.z,wx=bx+28*Math.sin(bz*.0068)-16*Math.sin((bx+bz)*.0042),wz=bz+22*Math.sin(bx*.0076)+12*Math.cos((bx-bz)*.0051),qx=wx/(1100*.47),qz=wz/(1100*.43),r=Math.sqrt(qx*qx+qz*qz);let m=1-r+.055*Math.sin(bx*.019)+.04*Math.sin(bz*.023)+.032*Math.sin((bx-bz)*.031);m+=gauss(bx,bz,360,-35,180)*.17+gauss(bx,bz,-330,150,150)*.11+gauss(bx,bz,35,-390,125)*.08-gauss(bx,bz,420,215,95)*.14-gauss(bx,bz,-455,-10,85)*.10-gauss(bx,bz,110,455,90)*.07;return m}
function riverCenter(z){const bz=z/SCALE;return(34*Math.sin(bz*.010)+15*Math.sin(bz*.027)-28+bz*.055)*SCALE}
function river2Center(z){const bz=z/SCALE;return(250-0.33*bz+30*Math.sin(bz*.012))*SCALE}
function riverAt(x,z){const bz=z/SCALE;return(Math.abs(x-riverCenter(z))<11*SCALE&&bz>-360&&bz<330)||(Math.abs(x-river2Center(z))<7*SCALE&&bz>40&&bz<325)}
function lakeAt(x,z){const p=U(x,z),bx=p.x,bz=p.z;return((bx-165)/82)**2+((bz+58)/60)**2<1||((bx+188)/66)**2+((bz-150)/50)**2<1||((bx-18)/58)**2+((bz-275)/41)**2<1||((bx-305)/48)**2+((bz-205)/34)**2<1}
function ridgeWest(x,z){const p=U(x,z),bx=p.x,bz=p.z,center=-275+.24*(bz+170)+31*Math.sin(bz*.009),d=Math.abs(bx-center),window=smooth(-430,-305,bz)*(1-smooth(120,265,bz));return Math.exp(-(d*d)/(86*86))*window}
function ridgeNorth(x,z){const p=U(x,z),bx=p.x,bz=p.z,center=242+40*Math.sin(bx*.008),d=Math.abs(bz-center),window=smooth(-350,-175,bx)*(1-smooth(405,515,bx));return Math.exp(-(d*d)/(96*96))*window}
function ridgeEast(x,z){const p=U(x,z),bx=p.x,bz=p.z,center=294-.13*bz+21*Math.sin(bz*.014),d=Math.abs(bx-center),window=smooth(-125,15,bz)*(1-smooth(325,445,bz));return Math.exp(-(d*d)/(110*110))*window}
function foothills(x,z){const p=U(x,z),bx=p.x,bz=p.z;return gauss(bx,bz,-115,-135,210)*.55+gauss(bx,bz,120,235,210)*.42+gauss(bx,bz,330,65,170)*.38}
function desertZone(x,z){const p=U(x,z),bx=p.x,bz=p.z;return smooth(65,205,bx)*(1-smooth(-10,105,bz))*smooth(-405,-245,bz)}
function rawHeight(x,z){const p=U(x,z),bx=p.x,bz=p.z,m=islandMask(x,z);if(m<-.04)return-9;const coast=smooth(.022,.19,m),deep=smooth(.12,.60,m);let h=1.1+coast*8.2+deep*11.8;const broad=Math.sin(bx*.0085)*3.5+Math.cos(bz*.0101)*3+Math.sin((bx+bz)*.0057)*4.6;const medium=Math.sin(bx*.022+bz*.0105)*2.3+Math.cos(bz*.026-bx*.008)*2.0;const fine=(Math.abs(Math.sin(bx*.056+bz*.030))-.5)*1.55;h+=(broad+medium+fine)*coast;const rw=ridgeWest(x,z),rn=ridgeNorth(x,z),re=ridgeEast(x,z);h+=rw*(88+22*Math.abs(Math.sin(bz*.034)))+rn*(59+15*Math.abs(Math.sin(bx*.028)))+re*(50+13*Math.abs(Math.cos(bz*.036)));h+=foothills(x,z)*19*coast;h+=gauss(bx,bz,-342,-98,118)*32+gauss(bx,bz,-205,-248,112)*28+gauss(bx,bz,125,38,185)*14+gauss(bx,bz,370,115,90)*18;
const valleyDist=Math.abs(x-riverCenter(z))/SCALE;h-=Math.exp(-(valleyDist*valleyDist)/(64*64))*smooth(-355,-275,bz)*(1-smooth(295,350,bz))*(10+deep*9);const valley2=Math.abs(x-river2Center(z))/SCALE;h-=Math.exp(-(valley2*valley2)/(43*43))*smooth(25,80,bz)*(1-smooth(300,345,bz))*8;
const dz=desertZone(x,z),duneMask=dz*(1-smooth(34,55,h));const dunes=(Math.sin(bx*.047+bz*.019)*.5+.5)*5.3+(Math.sin(bx*.025-bz*.038)*.5+.5)*3.1;h+=duneMask*dunes;const mesas=dz*(gauss(bx,bz,295,-205,58)*17+gauss(bx,bz,390,-125,45)*13+gauss(bx,bz,235,-305,52)*11);h+=mesas;
const westCliff=smooth(-430,-255,-bx)*smooth(18,170,bz)*smooth(.075,.165,m)*(1-smooth(.175,.29,m));h+=westCliff*14;const eastCliff=smooth(320,425,bx)*smooth(-30,130,bz)*smooth(.085,.17,m)*(1-smooth(.18,.28,m));h+=eastCliff*9;
const southBeach=(1-smooth(-440,-270,bz))*smooth(.02,.16,m);h=lerp(h,1.0+Math.max(0,m)*19,southBeach*.78);const northBeach=smooth(320,445,bz)*smooth(.02,.13,m);h=lerp(h,1.4+Math.max(0,m)*17,northBeach*.52);
if(riverAt(x,z))h=Math.min(h,-2.6);if(lakeAt(x,z))h=Math.min(h,-3.3);return h}
function heightAt(x,z){return rawHeight(x,z)}
function slopeAt(x,z){const e=6*SCALE,hx=heightAt(x+e,z)-heightAt(x-e,z),hz=heightAt(x,z+e)-heightAt(x,z-e);return Math.sqrt(hx*hx+hz*hz)/(e*2)}
function climateAt(x,z){const p=U(x,z),bx=p.x,bz=p.z,h=heightAt(x,z),m=islandMask(x,z),waterDist=Math.min(Math.abs(x-riverCenter(z)),Math.abs(x-river2Center(z)))/SCALE,wetRiver=1-smooth(18,125,waterDist),wetLakes=Math.max(gauss(bx,bz,165,-58,155),gauss(bx,bz,-188,150,135),gauss(bx,bz,18,275,120),gauss(bx,bz,305,205,95)),macro=noise(bx*.012+9,bz*.012-6),detail=noise(bx*.035-3,bz*.035+4);const coast=1-smooth(.075,.24,m),cold=clamp01(smooth(44,86,h)+ridgeWest(x,z)*.20+ridgeNorth(x,z)*.12),desert=clamp01(desertZone(x,z)*(.68+.32*macro)*(1-wetRiver*.84)*(1-wetLakes*.80)),jungle=clamp01(smooth(20,155,bx)*smooth(25,165,bz)*(.55+.45*detail)+wetRiver*.36+wetLakes*.48),coastal=clamp01(smooth(45,225,-bx)*smooth(10,155,bz)*(.58+.42*macro)+coast*.35),river=clamp01(wetRiver*smooth(-330,-240,bz)*smooth(345,245,bz));return{h,m,coast,cold,desert,jungle,coastal,river,wet:clamp01(wetRiver*.7+wetLakes*.8),slope:slopeAt(x,z)}}
function biomeAt(x,z){const c=climateAt(x,z);if(c.h<=WATER+.2)return'Eau';if(c.m<.10&&c.slope<.52)return'Plage';if(c.cold>.72)return'Neige';if(c.h>50&&c.slope>.20)return'Montagnes';if(c.desert>.64)return'Désert';if(c.desert>.34)return'Savane';if(c.jungle>.64)return'Jungle';if(c.jungle>.37)return'Forêt tropicale';if(c.coastal>.60)return'Côte sauvage';if(c.river>.50)return'Vallée fluviale';if(c.cold>.38)return'Toundra';return'Prairies'}
function terrainColor(x,z){const c=climateAt(x,z);if(c.h<=WATER+.2)return new THREE.Color(0x2b7897);const base=new THREE.Color(0x6f954d),mix=new THREE.Color(),blend=(hex,w)=>{if(w<=0)return;mix.set(hex);base.lerp(mix,clamp01(w))};blend(0xd8bd78,c.coast*.90*(1-clamp01(c.slope*1.2)));blend(0xc89b54,c.desert*.86);blend(0xa78f50,c.desert*(1-c.desert)*.68);blend(0x255b32,c.jungle*.82);blend(0x3d7640,c.jungle*(1-c.jungle)*.68);blend(0x4c7048,c.coastal*.42);blend(0x4f8a51,c.river*.62);blend(0x6d716f,clamp01(c.slope*1.05)*smooth(28,54,c.h));blend(0x777b77,smooth(48,70,c.h)*.75);blend(0xe8eef0,c.cold*.90);return base}
const geo=new THREE.PlaneGeometry(SIZE,SIZE,250,250);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position,colors=[];
for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),h=heightAt(x,z),cc=terrainColor(x,z);pos.setY(i,h);const p=U(x,z),shade=.88+noise(p.x*.15,p.z*.15)*.16;cc.multiplyScalar(shade);colors.push(cc.r,cc.g,cc.b)}
geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const land=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.97}));land.receiveShadow=true;scene.add(land);
const ocean=new THREE.Mesh(new THREE.PlaneGeometry(2500,2500),new THREE.MeshStandardMaterial({color:0x277c9f,transparent:true,opacity:.82,roughness:.18,metalness:.04}));ocean.rotation.x=-Math.PI/2;ocean.position.y=WATER;scene.add(ocean);
function landOK(x,z,pad=1){return islandMask(x,z)>.03&&heightAt(x,z)>WATER+pad&&!riverAt(x,z)&&!lakeAt(x,z)}
function tree(x,z,s=1,jungle=false,snow=false){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.6,.95,6.4,7),new THREE.MeshStandardMaterial({color:jungle?0x4a331f:0x513824,roughness:1}));let c1,c2;if(jungle){c1=new THREE.Mesh(new THREE.SphereGeometry(3.5,8,6),new THREE.MeshStandardMaterial({color:0x1f6733,roughness:1}));c2=new THREE.Mesh(new THREE.SphereGeometry(2.9,8,6),new THREE.MeshStandardMaterial({color:0x2f7d3d,roughness:1}));c1.position.y=8;c2.position.set(1.2,10.2,.4)}else{c1=new THREE.Mesh(new THREE.ConeGeometry(4.1,9.5,8),new THREE.MeshStandardMaterial({color:snow?0x6d8772:0x244f2b,roughness:1}));c2=new THREE.Mesh(new THREE.ConeGeometry(3.4,7.5,8),new THREE.MeshStandardMaterial({color:snow?0xdde7e3:0x326538,roughness:1}));c1.position.y=8.2;c2.position.y=12.3}tr.position.y=3.2;tr.castShadow=c1.castShadow=c2.castShadow=true;g.add(tr,c1,c2);g.position.set(x,heightAt(x,z),z);g.scale.setScalar(s);scene.add(g)}
function palm(x,z,s=1){const g=new THREE.Group(),tr=new THREE.Mesh(new THREE.CylinderGeometry(.45,.7,7.5,7),new THREE.MeshStandardMaterial({color:0x73502f,roughness:1}));tr.position.y=3.7;g.add(tr);for(let k=0;k<6;k++){const leaf=new THREE.Mesh(new THREE.ConeGeometry(.65,5.2,5),new THREE.MeshStandardMaterial({color:0x3c7b3e,roughness:1}));leaf.position.y=7.7;leaf.rotation.z=Math.PI/2.6;leaf.rotation.y=k*Math.PI/3;g.add(leaf)}g.position.set(x,heightAt(x,z),z);g.scale.setScalar(s);scene.add(g)}
function cactus(x,z,s=1){const mat=new THREE.MeshStandardMaterial({color:0x4f7d45,roughness:1}),g=new THREE.Group(),main=new THREE.Mesh(new THREE.CylinderGeometry(.55,.75,6,7),mat);main.position.y=3;g.add(main);for(const side of[-1,1]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.3,.38,2.7,7),mat);arm.position.set(side*.8,3.4,0);arm.rotation.z=side*.75;g.add(arm)}g.position.set(x,heightAt(x,z),z);g.scale.setScalar(s);scene.add(g)}
function rock(x,z,metal=false,snow=false){const base=metal?2.9:2.2+noise(x/SCALE,z/SCALE)*3.2,m=new THREE.Mesh(new THREE.DodecahedronGeometry(base,1),new THREE.MeshStandardMaterial({color:snow?0xc9d1d2:metal?0x52636d:0x767d78,roughness:metal?.48:.95,metalness:metal?.55:0}));m.scale.set(1,.72+noise(z/SCALE,x/SCALE)*.45,.8+noise(x/SCALE+2,z/SCALE+8)*.5);m.rotation.set(noise(x/SCALE,1),noise(z/SCALE,2)*Math.PI,noise(x/SCALE,z/SCALE));m.position.set(x,heightAt(x,z)+base*.7,z);m.castShadow=true;m.receiveShadow=true;scene.add(m)}
function bush(x,z,jungle=false){const g=new THREE.Group();for(let k=0;k<4;k++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(1.35+k*.18,1),new THREE.MeshStandardMaterial({color:jungle?(k%2?0x246a35:0x318241):(k%2?0x3f743c:0x4d8244),roughness:1}));m.position.set((k-1.5)*.9,1.15+Math.sin(k)*.12,Math.cos(k)*.85);g.add(m)}g.position.set(x,heightAt(x,z),z);g.scale.setScalar(.8+noise(x/SCALE,z/SCALE)*.6);scene.add(g)}
function grassPatch(x,z,jungle=false){const g=new THREE.Group();for(let k=0;k<4;k++){const m=new THREE.Mesh(new THREE.ConeGeometry(.23,1.7+noise(x/SCALE+k,z/SCALE)*.8,3),new THREE.MeshStandardMaterial({color:jungle?(k%2?0x4f9b4d:0x397c40):(k%2?0x789b43:0x65893a),roughness:1}));m.position.set((k-1.5)*.4,.9,Math.sin(k*2)*.35);g.add(m)}g.position.set(x,heightAt(x,z),z);g.rotation.y=noise(x/SCALE,z/SCALE)*Math.PI;scene.add(g)}
for(let i=0;i<760;i++){let x=(noise(i,11)-.5)*SIZE*.89,z=(noise(i,29)-.5)*SIZE*.85,b=biomeAt(x,z),c=climateAt(x,z);if(!landOK(x,z,2)||c.slope>.55)continue;const r=noise(i,8);if((b==='Jungle'||b==='Forêt tropicale')&&r>1-(.34+c.jungle*.52))tree(x,z,.7+noise(i,4)*.9,true,false);else if((b==='Prairies'||b==='Vallée fluviale'||b==='Côte sauvage'||b==='Savane')&&r>.68+c.desert*.18)tree(x,z,.65+noise(i,4)*.8,false,false);else if((b==='Neige'||b==='Toundra')&&r>.76+c.cold*.08)tree(x,z,.62+noise(i,4)*.7,false,true);else if(b==='Plage'&&r>.89)palm(x,z,.8+noise(i,4)*.5)}
for(let i=0;i<165;i++){let x=(noise(i,201)-.5)*SIZE*.82,z=(noise(i,207)-.5)*SIZE*.78,b=biomeAt(x,z),c=climateAt(x,z);if(landOK(x,z,2)&&(b==='Désert'||b==='Savane')&&c.slope<.40&&noise(i,211)>.42-c.desert*.25)cactus(x,z,.7+noise(i,219)*.8)}
for(let i=0;i<350;i++){let x=(noise(i,41)-.5)*SIZE*.90,z=(noise(i,53)-.5)*SIZE*.84,b=biomeAt(x,z),s=slopeAt(x,z);if(landOK(x,z,1.5)&&noise(i,59)>.60-Math.min(.38,s*.50))rock(x,z,false,b==='Neige'||b==='Toundra')}
for(let i=0;i<92;i++){let x=(noise(i,71)-.5)*SIZE*.78,z=(noise(i,83)-.5)*SIZE*.76;if(landOK(x,z,2)&&heightAt(x,z)>14)rock(x,z,true,false)}
for(let i=0;i<410;i++){let x=(noise(i,97)-.5)*SIZE*.86,z=(noise(i,107)-.5)*SIZE*.82,b=biomeAt(x,z),c=climateAt(x,z);if(landOK(x,z,1)&&c.slope<.46&&(b==='Jungle'||b==='Forêt tropicale'||b==='Prairies'||b==='Vallée fluviale'||b==='Côte sauvage'||b==='Savane')&&noise(i,114)>.25+c.desert*.35)bush(x,z,c.jungle>.42)}
for(let i=0;i<860;i++){let x=(noise(i,131)-.5)*SIZE*.85,z=(noise(i,149)-.5)*SIZE*.80,b=biomeAt(x,z),c=climateAt(x,z);if(landOK(x,z,.8)&&heightAt(x,z)<46&&c.slope<.38&&(b==='Jungle'||b==='Forêt tropicale'||b==='Prairies'||b==='Vallée fluviale'||b==='Côte sauvage'||b==='Savane')&&noise(i,157)>.14+c.desert*.42)grassPatch(x,z,c.jungle>.42)}
const body=new THREE.Group(),torso=new THREE.Mesh(new THREE.CapsuleGeometry(1.8,3.4,5,8),new THREE.MeshStandardMaterial({color:0x574331})),head=new THREE.Mesh(new THREE.SphereGeometry(1.35,12,10),new THREE.MeshStandardMaterial({color:0xb9825c}));torso.position.y=4;head.position.y=7.2;torso.castShadow=head.castShadow=true;body.add(torso,head);scene.add(body);
function coastalSpawn(){for(let i=0;i<1400;i++){const a=noise(i,313)*Math.PI*2,r=(390+noise(i,317)*55)*SCALE,x=Math.cos(a)*r,z=Math.sin(a)*r;if(landOK(x,z,1)&&slopeAt(x,z)<.32)return{x,z}}return{x:0,z:350*SCALE}}
const ctx=miniMap.getContext('2d'),mapBase=document.createElement('canvas');mapBase.width=mapBase.height=MAP_RES;const mc=mapBase.getContext('2d');
function buildMap(){const im=mc.createImageData(MAP_RES,MAP_RES),tmp=new THREE.Color();for(let y=0;y<MAP_RES;y++)for(let x=0;x<MAP_RES;x++){const wx=(x/(MAP_RES-1)-.5)*SIZE,wz=(.5-y/(MAP_RES-1))*SIZE;let c;if(riverAt(wx,wz)||lakeAt(wx,wz)||heightAt(wx,wz)<=WATER+.2)c=[35,120,151];else{tmp.copy(terrainColor(wx,wz));c=[tmp.r*255,tmp.g*255,tmp.b*255]}const p=(y*MAP_RES+x)*4;im.data[p]=c[0];im.data[p+1]=c[1];im.data[p+2]=c[2];im.data[p+3]=255}mc.putImageData(im,0,0)}buildMap();
function headingDeg(){return ((yaw*180/Math.PI)%360+360)%360}
function drawMiniMap(){const w=miniMap.width,h=miniMap.height,s=w/SIZE;ctx.clearRect(0,0,w,h);ctx.drawImage(mapBase,0,0,w,h);const mx=w/2+px*s,my=h/2-pz*s;ctx.save();ctx.translate(mx,my);ctx.rotate(yaw);ctx.fillStyle='#ffe18c';ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(7,8);ctx.lineTo(0,5);ctx.lineTo(-7,8);ctx.closePath();ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#172027';ctx.stroke();ctx.restore()}
function updateCompass(){const deg=headingDeg(),dirs=['N','NE','E','SE','S','SO','O','NO'],idx=Math.round(deg/45)%8;compassStrip.innerHTML=dirs[(idx+7)%8]+' · <span class="card">'+dirs[idx]+'</span> · '+dirs[(idx+1)%8]+' &nbsp; '+Math.round(deg)+'°'}
function setStat(id,fill,value){const v=Math.max(0,Math.min(100,Number(value)||0));document.getElementById(id).textContent=Math.round(v);document.getElementById(fill).style.width=v+'%'}
function updateCamera(){const ground=Math.max(WATER+.15,heightAt(px,pz)),eye=ground+6.25;body.position.set(px,ground,pz);body.rotation.y=yaw;const look=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));if(third){body.visible=true;const target=new THREE.Vector3(px,eye,pz),desired=new THREE.Vector3(px-Math.sin(yaw)*10,eye+3.8,pz+Math.cos(yaw)*10);camera.position.lerp(desired,.28);camera.lookAt(target.clone().add(look.multiplyScalar(3)))}else{body.visible=false;camera.position.set(px,eye,pz);camera.lookAt(camera.position.clone().add(look))}topinfo.textContent=(character?.name||'Survivant')+' • '+biomeAt(px,pz)+' • '+(sessionStorage.getItem('survival_server_name')||'Serveur');updateCompass();drawMiniMap()}
async function savePosition(force=false){if(!character)return;const n=Date.now();if(!force&&n-lastSave<3000)return;lastSave=n;await sb.from('characters').update({position_x:px,position_y:pz,biome:biomeAt(px,pz),has_spawned:true}).eq('id',character.id)}
function loop(now){const dt=Math.min(.035,(now-lastTime)/1000||.016);lastTime=now;if(Math.abs(moveX)>.02||Math.abs(moveY)>.02){const fX=Math.sin(yaw),fZ=-Math.cos(yaw),rX=Math.cos(yaw),rZ=Math.sin(yaw),speed=36;px+=(fX*moveY+rX*moveX)*speed*dt;pz+=(fZ*moveY+rZ*moveX)*speed*dt;px=Math.max(-SIZE*.49,Math.min(SIZE*.49,px));pz=Math.max(-SIZE*.49,Math.min(SIZE*.49,pz));savePosition()}updateCamera();renderer.render(scene,camera);requestAnimationFrame(loop)}
function setupControls(){let moveTouch=null,lookTouch=null,cx=0,cy=0,lx=0,ly=0;joystick.addEventListener('touchstart',e=>{const t=e.changedTouches[0],r=joystick.getBoundingClientRect();moveTouch=t.identifier;cx=r.left+r.width/2;cy=r.top+r.height/2},{passive:false});joystick.addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===moveTouch){let dx=t.clientX-cx,dy=t.clientY-cy,d=Math.hypot(dx,dy)||1,m=Math.min(38,d),power=Math.min(1,d/34);moveX=dx/d*power;moveY=-dy/d*power;stick.style.transform=`translate(${dx/d*m}px,${dy/d*m}px)`}e.preventDefault()},{passive:false});function moveEnd(e){for(const t of e.changedTouches)if(t.identifier===moveTouch){moveTouch=null;moveX=moveY=0;stick.style.transform=''}}joystick.addEventListener('touchend',moveEnd);joystick.addEventListener('touchcancel',moveEnd);renderer.domElement.addEventListener('touchstart',e=>{for(const t of e.changedTouches){if(t.clientX>innerWidth*.38&&lookTouch===null){lookTouch=t.identifier;lx=t.clientX;ly=t.clientY;break}}},{passive:false});renderer.domElement.addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===lookTouch){const dx=t.clientX-lx,dy=t.clientY-ly;yaw+=dx*.0042;pitch=Math.max(-1.15,Math.min(1.05,pitch-dy*.0036));lx=t.clientX;ly=t.clientY}e.preventDefault()},{passive:false});function lookEnd(e){for(const t of e.changedTouches)if(t.identifier===lookTouch)lookTouch=null}renderer.domElement.addEventListener('touchend',lookEnd);renderer.domElement.addEventListener('touchcancel',lookEnd);viewBtn.onclick=()=>{third=!third;viewBtn.textContent=third?'3e PERSONNE':'1re PERSONNE'}}
async function enterWorld(){const id=sessionStorage.getItem('survival_character_id'),auth=await sb.auth.getUser();if(!auth.data.user||!id){location.href='characters.html';return}const r=await sb.from('characters').select('*').eq('id',id).single();if(r.error||!r.data){location.href='characters.html';return}character=r.data;setStat('life','lifeFill',character.life);setStat('hunger','hungerFill',character.hunger);setStat('thirst','thirstFill',character.thirst);setStat('energy','energyFill',character.energy);if(character.has_spawned&&character.position_x!=null&&Math.abs(character.position_x)<SIZE*.49&&Math.abs(character.position_y)<SIZE*.49){px=character.position_x;pz=character.position_y;spawnText.textContent='Retour dans '+biomeAt(px,pz)+'...'}else{const p=coastalSpawn();px=p.x;pz=p.z;spawnText.textContent='Nouveau survivant — arrivée sur la côte...';await savePosition(true)}setupControls();viewBtn.textContent='1re PERSONNE';setTimeout(()=>spawn.classList.add('hide'),1000);requestAnimationFrame(loop)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('pagehide',()=>savePosition(true));enterWorld();