import {RACES} from './rules.js?v=ew5';
export const HAIRSTYLES=[['short','Courte'],['long','Longue'],['braids','Tresses'],['ponytail','Queue de cheval'],['shaved','Crâne rasé'],['mohawk','Crête']];
export const BEARDS=[['none','Sans barbe'],['stubble','Barbe courte'],['full','Barbe longue'],['braided','Barbe tressée']];
export const SKINS={human:['#f0d0b0','#dfb58c','#c99770','#a47755','#805c42','#533c30'],elf:['#edddd0','#d5b7a0','#b6a38d','#8f8672','#736e5e','#514e47'],orc:['#a4b68a','#82986b','#657954','#53674a','#8b8862','#444f40'],dwarf:['#e9c4a2','#d4aa86','#c09172','#a97856','#825d43','#63483a'],draconian:['#c8a47c','#b17355','#945b47','#79534b','#625152','#483e3d'],snow:['#e4e8e9','#d0dbe0','#b0c3ce','#91a8b9','#788d9d','#627785'],trees:['#b7ad88','#928368','#7c7457','#667053','#576246','#454e3f'],desert:['#dec19a','#c89f74','#ad805d','#956c4e','#74553d','#59412f']};
const hex=(value,fallback)=>typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value.toLowerCase():fallback;
export function appearanceDefaults(race='human'){return {skin:SKINS[race]?.[2]||SKINS.human[2],hair:'short',hairColor:race==='snow'?'#d9dfe1':'#47392b',eyes:race==='draconian'?'#dba657':'#7c9b83',beard:race==='dwarf'?'full':'none',marks:'none',stature:1};}
export function validateAppearance(value={},race='human'){value=value&&typeof value==='object'?value:{};const d=appearanceDefaults(race);return {skin:hex(value.skin,d.skin),hair:HAIRSTYLES.some(x=>x[0]===value.hair)?value.hair:d.hair,hairColor:hex(value.hairColor,d.hairColor),eyes:hex(value.eyes,d.eyes),beard:BEARDS.some(x=>x[0]===value.beard)?value.beard:d.beard,marks:['none','freckles','scar'].includes(value.marks)?value.marks:d.marks,stature:[.94,1,1.06].includes(Number(value.stature))?Number(value.stature):1};}
export function validateCharacter(value){if(!value||typeof value.id!=='string'||!value.id||typeof value.name!=='string'||!value.name.trim()||!RACES.some(r=>r.id===value.race))return null;return {id:value.id,name:value.name.trim().slice(0,24),race:value.race,body:value.body==='female'?'female':'male',appearance:validateAppearance(value.appearance,value.race),createdAt:Number(value.createdAt)||0};}
export function loadCharacters(storage){let roster=[],active=null;try{const raw=JSON.parse(storage.getItem('everwild-characters')||'[]');if(Array.isArray(raw))roster=raw.map(validateCharacter).filter(Boolean);const seen=new Set();roster=roster.filter(p=>{if(seen.has(p.id))return false;seen.add(p.id);return true;});active=validateCharacter(JSON.parse(storage.getItem('everwild-profile')||'null'));if(active&&!seen.has(active.id))roster.unshift(active);if(active)active=roster.find(p=>p.id===active.id)||null;}catch{}return {roster,active:active||roster[0]||null};}
export function persistCharacters(storage,roster,active){const list=roster.map(validateCharacter).filter(Boolean);storage.setItem('everwild-characters',JSON.stringify(list));if(active)storage.setItem('everwild-profile',JSON.stringify(validateCharacter(active)));return list;}
