import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {photographicMaterial} from './pbr.js?v=ew5';
import {landDistance,regionAt} from './geography.js?v=ew5';
export const noise=n=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v);};
const textures=new Map(),materials=new Map(),trees=new Map();
export function surface(kind='stone'){
 if(textures.has(kind))return textures.get(kind);
 const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),im=ctx.createImageData(512,512);
 for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4,grain=noise(x+y*512),low=Math.sin(x*.043+Math.sin(y*.024))*Math.cos(y*.053)*.5;
  let value=kind==='bark'?180+35*Math.sin(x*.19+Math.sin(y*.031)*2)+18*Math.sin(x*.48+y*.015)+grain*15:kind==='fur'?205+grain*20+13*Math.sin(x*.067+y*.031):kind==='cap'?204+23*Math.sin(x*.031)*Math.cos(y*.049)+grain*10:kind==='cloth'?215+((x%4===0||y%4===0)?-32:0)+grain*12:205+low*37+(grain-.5)*28;
  im.data[i]=im.data[i+1]=im.data[i+2]=value;im.data[i+3]=255;
 }ctx.putImageData(im,0,0);
 if(kind==='bark'){for(let k=0;k<120;k++){const x=noise(k)*512,y=noise(k+70)*512;ctx.lineWidth=.5+noise(k+20)*2.6;ctx.strokeStyle=k%3?'rgba(35,31,24,.55)':'rgba(255,249,226,.35)';ctx.beginPath();ctx.moveTo(x,y);ctx.bezierCurveTo(x+3,y+12,x-2,y+31,x+noise(k+1)*9-4,y+40+noise(k+4)*70);ctx.stroke();}}
 if(kind==='fur'){for(let k=0;k<8500;k++){const x=noise(k)*512,y=noise(k+8900)*512;ctx.strokeStyle=k%3?'rgba(65,55,42,.22)':'rgba(255,251,235,.38)';ctx.lineWidth=.65;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+2,y+4+noise(k+220)*8);ctx.stroke();}}
 if(kind==='stone'){for(let k=0;k<240;k++){const x=noise(k)*512,y=noise(k+600)*512;ctx.strokeStyle='rgba(61,59,50,.24)';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+15+noise(k+1)*35,y+noise(k+30)*12);ctx.stroke();}}
 const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;map.wrapS=map.wrapT=THREE.RepeatWrapping;map.anisotropy=4;const bump=map.clone();bump.colorSpace=THREE.NoColorSpace;const value={map,bump};textures.set(kind,value);return value;
}
export function naturalMaterial(kind,color,roughness=.9){const key=kind+color+roughness;if(materials.has(key))return materials.get(key);const tex=surface(kind),mat=new THREE.MeshStandardMaterial({color,map:tex.map,bumpMap:tex.bump,bumpScale:kind==='bark'?.09:kind==='fur'?.024:.05,roughness,metalness:0});photographicMaterial(mat,kind);materials.set(key,mat);return mat;}
let foliageTexture;
export function leafTexture(){if(foliageTexture)return foliageTexture;const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#b4c3a7';ctx.beginPath();ctx.moveTo(64,5);ctx.bezierCurveTo(110,42,111,88,64,123);ctx.bezierCurveTo(16,88,18,42,64,5);ctx.fill();ctx.strokeStyle='#97a887';ctx.lineWidth=.75;ctx.beginPath();ctx.moveTo(64,5);ctx.lineTo(64,124);ctx.stroke();for(let i=0;i<9;i++){const y=20+i*10;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(64,y+16);ctx.lineTo(64+side*(18+Math.sin(i/9*Math.PI)*20),y);ctx.stroke();}}foliageTexture=new THREE.CanvasTexture(c);foliageTexture.colorSpace=THREE.SRGBColorSpace;return foliageTexture;}
function leafMat(color){const key='leaf'+color;if(materials.has(key))return materials.get(key);const m=new THREE.MeshStandardMaterial({color,map:leafTexture(),alphaTest:.42,side:THREE.DoubleSide,roughness:.83});m.userData.isLeafCard=true;materials.set(key,m);return m;}
function branch(a,b,r1,r2,seed=0){const length=a.distanceTo(b),geo=new THREE.CylinderGeometry(r2,r1,length,10,4);const p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),y=p.getY(i),f=1+Math.sin(Math.atan2(z,x)*5+y*2+seed)*.055;p.setXYZ(i,x*f,y,z*f);}geo.computeVertexNormals();const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());geo.applyQuaternion(q);geo.translate(...a.clone().add(b).multiplyScalar(.5).toArray());return geo;}
function addMesh(parent,geo,mat,pos=[0,0,0],scale=[1,1,1]){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.scale.set(...scale);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
export function naturalTree(variant=0,season=0,pine=false){
 const key=variant%6+':'+season+':'+pine;if(trees.has(key)){const clone=trees.get(key).clone(true);clone.userData.crown=clone.getObjectByName('NaturalCanopy');return clone;}
 const g=new THREE.Group();g.name=pine?'NaturalFir':'NaturalOak';const seed=variant*53+17,height=pine?7.6:6.4+noise(seed)*1.8;
 const trunkMat=naturalMaterial('bark',pine?0x6b6050:0x766450),parts=[];const bend=(noise(seed)-.5)*.7;
 const a=new THREE.Vector3(0,.02,0),b=new THREE.Vector3(bend*.3,height*.43,0),c=new THREE.Vector3(bend,height*.79,.15),d=new THREE.Vector3(bend*.9,height,.1);
 parts.push(branch(a,b,.38,.24,seed),branch(b,c,.24,.14,seed+2),branch(c,d,.14,.028,seed+4));
 for(let i=0;i<6;i++){const angle=i*Math.PI/3;parts.push(branch(new THREE.Vector3(0,.2,0),new THREE.Vector3(Math.cos(angle)*.9,.05,Math.sin(angle)*.9),.14,.014,seed+i));}
 const crown=new THREE.Group();crown.name='NaturalCanopy';g.add(crown);const leaves=[],colors=[];
 if(pine){for(let level=0;level<10;level++){const y=height*.24+level*height*.071,radius=(1-level/11)*1.9;for(let j=0;j<5;j++){const angle=j*Math.PI*.4+level*.7;const end=new THREE.Vector3(Math.cos(angle)*radius,y-.25,Math.sin(angle)*radius);parts.push(branch(new THREE.Vector3(bend*y/height,y,0),end,.042,.008,seed+j));for(let k=0;k<12;k++){const t=k/12;leaves.push([end.x*t,y-.22*t,end.z*t,.35,.7,angle+noise(k+seed)*.5,noise(k)*.5]);colors.push(0x6c8269);}}}}
 else{for(let j=0;j<10;j++){const angle=j*2.399+seed,y=height*.47+noise(j+seed)*height*.28,radius=1.7+noise(j+seed+9)*.9;const end=new THREE.Vector3(Math.cos(angle)*radius,y+.9,Math.sin(angle)*radius);parts.push(branch(new THREE.Vector3(bend*.5,y,0),end,.09,.017,seed+j));for(let k=0;k<42;k++){const az=noise(k+j*42)*6.28,r=Math.sqrt(noise(k+seed+11))*1.05;leaves.push([end.x+Math.cos(az)*r,end.y+(noise(k+30)-.5)*1.6,end.z+Math.sin(az)*r,.24,.39,noise(k+101)*6.28,(noise(k+111)-.5)*2.1]);colors.push(season===2?[0xc89056,0xa6683e,0xd2a16b][k%3]:[0x7f9666,0x607b4c,0x9fa87a][k%3]);}}}
 addMesh(g,mergeGeometries(parts.slice(0,9),false),trunkMat);addMesh(crown,mergeGeometries(parts.slice(9),false),trunkMat);parts.forEach(p=>p.dispose());
 const foliage=new THREE.InstancedMesh(new THREE.PlaneGeometry(1,1),leafMat(season===3?0xb0bcb2:0xffffff),leaves.length),dummy=new THREE.Object3D();for(let i=0;i<leaves.length;i++){const [x,y,z,sx,sy,ry,rx]=leaves[i];dummy.position.set(x,y,z);dummy.rotation.set(rx,ry,noise(i+seed)*.9);dummy.scale.set(sx,sy,1);dummy.updateMatrix();foliage.setMatrixAt(i,dummy.matrix);foliage.setColorAt(i,new THREE.Color(colors[i]));}foliage.castShadow=foliage.receiveShadow=true;crown.add(foliage);
 g.userData={kind:'tree',crown,windPhase:noise(seed)*6,treeKind:pine?'pine':'oak',natural:true,height};trees.set(key,g);return g;
}
export function naturalRock(kind='rock',variant=0,season=0){const g=new THREE.Group();g.userData.kind=kind;const color=kind==='iron'?0x787977:kind==='gold'?0x8a8067:season===3?0x929e9e:0x8d9084;for(let j=0;j<3;j++){const geo=new THREE.IcosahedronGeometry(.75,2),p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),f=1+.13*Math.sin(x*7+y*5+z*8+variant+j)+.07*Math.sin(x*15-z*10);p.setXYZ(i,x*f,Math.max(-.22,y*f),z*f);}geo.computeVertexNormals();addMesh(g,geo,naturalMaterial('stone',color),[(j-1)*.48,.27+(j%2)*.2,(noise(j+variant)-.5)*.55],[1,.6+(j%2)*.4,.85]);}return g;}
export function naturalMushroom(seed=0){const g=new THREE.Group();g.userData.kind='tree';const stem=naturalMaterial('bark',0xcec5b5),cap=naturalMaterial('cap',seed%2?0x947b94:0x8e8d97,.72),points=[];for(let i=0;i<12;i++){const y=i/11*2.8,r=.16+.08*Math.sin(i*.34);points.push(new THREE.Vector2(r,y));}const stalk=addMesh(g,new THREE.LatheGeometry(points,16),stem);stalk.rotation.z=(noise(seed)-.5)*.12;
 const profile=[[0,2.93],[.30,2.96],[.76,2.90],[1.1,2.73],[1.35,2.47],[1.39,2.32],[1.15,2.25],[.7,2.36],[.19,2.52],[0,2.52]].map(([r,y])=>new THREE.Vector2(r,y));addMesh(g,new THREE.LatheGeometry(profile,28),cap);
 const ribs=[];for(let i=0;i<28;i++){const angle=i/28*Math.PI*2;const a=new THREE.Vector3(Math.cos(angle)*.2,2.51,Math.sin(angle)*.2),b=new THREE.Vector3(Math.cos(angle)*1.32,2.31,Math.sin(angle)*1.32);ribs.push(branch(a,b,.018,.008,i));}addMesh(g,mergeGeometries(ribs,false),naturalMaterial('cap',0xd8cabb));ribs.forEach(p=>p.dispose());const ring=addMesh(g,new THREE.TorusGeometry(.25,.065,6,20),stem,[0,1.98,0]);ring.rotation.x=Math.PI/2;return g;}
export function naturalPalm(seed=0){const g=new THREE.Group(),parts=[];for(let i=0;i<5;i++)parts.push(branch(new THREE.Vector3(i*.045,i*1.1,0),new THREE.Vector3((i+1)*.045,(i+1)*1.1,0),.23-i*.025,.2-i*.025,i));addMesh(g,mergeGeometries(parts,false),naturalMaterial('bark',0x8f8067));parts.forEach(p=>p.dispose());const crown=new THREE.Group();g.add(crown);for(let i=0;i<9;i++){const angle=i/9*6.28,dir=new THREE.Vector3(Math.cos(angle),0,Math.sin(angle));const points=[new THREE.Vector3(.2,5.5,0),dir.clone().multiplyScalar(1.1).add(new THREE.Vector3(.2,5.9,0)),dir.clone().multiplyScalar(2.8).add(new THREE.Vector3(.2,4.8,0))];const stem=new THREE.CatmullRomCurve3(points);addMesh(crown,new THREE.TubeGeometry(stem,10,.03,5,false),naturalMaterial('bark',0x939269));const leaflets=new THREE.InstancedMesh(new THREE.PlaneGeometry(.16,.9),leafMat(0x819367),30),dummy=new THREE.Object3D();for(let k=0;k<30;k++){const t=k/30,p=stem.getPoint(t),side=k%2?1:-1;dummy.position.copy(p).add(new THREE.Vector3(-dir.z,0,dir.x).multiplyScalar(side*.35));dummy.rotation.set(-.55,angle+side*.6,Math.PI*.5);dummy.scale.set(1,.5+Math.sin(t*Math.PI),1);dummy.updateMatrix();leaflets.setMatrixAt(k,dummy.matrix);}leaflets.castShadow=true;crown.add(leaflets);}g.userData={kind:'tree',crown,windPhase:seed};return g;}
export function detailAnimal(root){root.traverse(o=>{if(!o.isMesh||!o.material?.color)return;const hex=o.material.color.getHex();if(o.geometry?.type==='IcosahedronGeometry'&&o.geometry.parameters?.detail<2){const radius=o.geometry.parameters.radius;const geo=new THREE.SphereGeometry(radius,18,12);o.geometry=geo;}if(!o.material.map&&o.material.metalness<.2){o.material=naturalMaterial('fur',hex,.87);}});}
// Biome-dependent local ground details: four draw calls, recycled as the player explores.
export function createUnderstory(scene,height){
 const root=new THREE.Group();root.name='NaturalUnderstory';scene.add(root);const capacity=1100,dummy=new THREE.Object3D();const leafGeo=new THREE.PlaneGeometry(.17,.45,1,3);leafGeo.translate(0,.20,0);
 const grass=new THREE.InstancedMesh(leafGeo,leafMat(0xb4bc9a),capacity),ferns=new THREE.InstancedMesh(new THREE.PlaneGeometry(.32,.55),leafMat(0xa1b38a),capacity),litter=new THREE.InstancedMesh(new THREE.PlaneGeometry(.18,.3),leafMat(0x9d8058),capacity),pebbles=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(.08,1),naturalMaterial('stone',0xa4a599),capacity);for(const m of [grass,ferns,litter,pebbles]){m.count=0;m.receiveShadow=true;m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);root.add(m);}let px=Infinity,pz=Infinity;
 function scatter(x,z){let counts=[0,0,0,0],meshes=[grass,ferns,litter,pebbles];for(let i=0;i<capacity;i++){const a=noise(i+100)*6.28,r=Math.sqrt(noise(i+700))*27,gx=x+Math.cos(a)*r,gz=z+Math.sin(a)*r;if(landDistance(gx,gz)<2)continue;const bio=regionAt(gx,gz).id;let type=['desert','volcanic','canyon','mountain','snow','island5'].includes(bio)?3:['tropical','swamp','mushroom'].includes(bio)?i%4===0?2:1:i%5===0?2:0;const m=meshes[type],n=counts[type]++,s=.6+noise(i+800)*.9;dummy.position.set(gx,height(gx,gz)+.035,gz);dummy.rotation.set(type===2?-Math.PI/2:0,noise(i+900)*6.28,type===0?(noise(i)-.5)*.25:0);dummy.scale.setScalar(type===1?s*1.2:s);dummy.updateMatrix();m.setMatrixAt(n,dummy.matrix);const color=new THREE.Color(bio==='snow'?0xf0efeb:bio==='desert'||bio==='canyon'?0xc0a485:bio==='volcanic'?0x777674:type===2?i%2?0xc4a079:0x927957:0xa9b494);m.setColorAt(n,color);}
 for(let i=0;i<4;i++){meshes[i].count=counts[i];meshes[i].instanceMatrix.needsUpdate=true;if(meshes[i].instanceColor)meshes[i].instanceColor.needsUpdate=true;meshes[i].computeBoundingSphere();}px=x;pz=z;}
 return {root,update(time,player){if(Math.hypot(player.x-px,player.z-pz)>5)scatter(player.x,player.z);grass.rotation.y=Math.sin(time*.08)*.004;}};
}
export function naturalCottage(){
 const g=new THREE.Group();g.name='StoneWoodCottage';const stone=[],wood=[],slates=[];
 const block=(parts,x,y,z,sx,sy,sz,rx=0,rz=0)=>{const geo=new THREE.BoxGeometry(sx,sy,sz);geo.rotateX(rx);geo.rotateZ(rz);geo.translate(x,y,z);parts.push(geo);};
 // Masonry walls with alternating courses, a doorway and warm mullioned windows.
 for(let row=0;row<9;row++)for(let col=0;col<11;col++){const x=-2.3+col*.44+(row%2)*.13,y=.18+row*.27;
  for(const side of [-1,1]){if(side===1&&Math.abs(x)<.6&&y<1.95)continue;if(side===1&&Math.abs(x+1.4)<.47&&y>.72&&y<1.65)continue;block(stone,x,y,side*1.55,.40,.235,.27);}
 }
 for(const side of [-1,1])for(let row=0;row<9;row++)for(let col=0;col<8;col++)block(stone,side*2.35,.18+row*.27,-1.45+col*.4,.27,.235,.36);
 for(const x of [-2.4,2.4])for(const z of [-1.6,1.6])block(wood,x,1.4,z,.17,2.75,.17);
 for(const z of [-1.61,1.61]){block(wood,0,2.48,z,5,.18,.16);for(const side of [-1,1])block(wood,side*1.15,3.13,z,3,.14,.14,0,-side*.47);}
 // Curved slate roof: small overlapping tiles rather than a pyramidal cap.
 for(const side of [-1,1])for(let row=0;row<7;row++)for(let col=0;col<14;col++){const z=side*(.08+row*.29),y=3.89-Math.abs(z)*.64+Math.abs(z*z)*.045;block(slates,-2.70+col*.41+(row%2)*.06,y,z,.43,.055,.45,side*.53);}
 block(wood,0,3.92,0,5.85,.14,.14);for(const side of [-1,1])block(wood,0,2.73,side*2.02,5.8,.16,.14);
 for(let row=0;row<14;row++)for(const x of [1.4,1.87])block(stone,x,2.25+row*.22,-.55,.40,.20,.58);
 for(const [parts,material] of [[stone,naturalMaterial('stone',0x9b9a8e)],[wood,naturalMaterial('bark',0x73614b)],[slates,naturalMaterial('stone',0x7a8790)]]){addMesh(g,mergeGeometries(parts,false),material);parts.forEach(p=>p.dispose());}
 const glow=new THREE.MeshStandardMaterial({color:0xf2c47d,emissive:0xd68c39,emissiveIntensity:1.2,roughness:.4});addMesh(g,new THREE.BoxGeometry(.78,.84,.045),glow,[-1.35,1.23,1.72]);for(const x of [-1.75,-1.35,-.95])addMesh(g,new THREE.BoxGeometry(.035,.90,.055),naturalMaterial('bark',0x685342),[x,1.23,1.76]);for(const y of [.82,1.23,1.65])addMesh(g,new THREE.BoxGeometry(.86,.035,.055),naturalMaterial('bark',0x685342),[-1.35,y,1.76]);
 const door=addMesh(g,new THREE.BoxGeometry(.88,1.8,.09),naturalMaterial('bark',0x897154),[.08,.94,1.72]);door.rotation.y=-.13;addMesh(g,new THREE.SphereGeometry(.04,8,6),new THREE.MeshStandardMaterial({color:0xd4bb7b,metalness:.65,roughness:.35}),[.4,1.02,1.79]);const lamp=new THREE.PointLight(0xffc78a,1.4,9,2);lamp.position.set(-1.2,1.6,2.1);g.add(lamp);return g;
}
